[application]
asset_dir = "assets"
out_dir = "dist"

[web.app]
title = "tmp-dioxus"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[bundle]
identifier = "com.shiki.tmp-dioxus"
publisher = "shiki"
copyright = "Copyright © 2025 shiki"
category = "DeveloperTools"
short_description = "Script Expression Tool"
long_description = "A visual programming tool for creating script expressions"
resources = ["assets/*"]

[bundle.windows]
webview_install_mode = { EmbedBootstrapper = { silent = true } }
icon_path = "assets/favicon.ico"
allow_downgrades = true
tsp = true
